import Head from 'next/head'
import { Inter } from '@next/font/google'
import NewsHome from './NewsHome'

const inter = Inter({ subsets: ['latin'] })

export default function index({api}) {
  return (
    <>
      <Head>
        <title>News Monkey</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <NewsHome api={api}/>
     
    </>
  )
}
