import Head from 'next/head'
import { Inter } from '@next/font/google'
import NewsHome from './NewsHome'

const inter = Inter({ subsets: ['latin'] })

export default function index({api}) {
  return (
    <>
      <Head>
        <title>News Monkey</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href=" <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="red"
              stroke="pink"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="1"
              className="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full"
              viewBox="0 0 24 24"
            >
              <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
            </svg>" />
      </Head>
      <NewsHome api={api}/>
     
    </>
  )
}
